# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: aome510.spotify-player
PackageVersion: 0.20.4
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: spotify_player.exe
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/aome510/spotify-player/releases/download/v0.20.4/spotify_player-x86_64-pc-windows-msvc.zip
    InstallerSha256: b93accfab33bcdc101f3ebf16ad0404632807f07e5f482368bfb91626c1ddd16
ManifestType: installer
ManifestVersion: 1.6.0
