# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: aome510.spotify-player
PackageVersion: 0.20.3
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: spotify_player.exe
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/aome510/spotify-player/releases/download/v0.20.3/spotify_player-x86_64-pc-windows-msvc.zip
    InstallerSha256: be3fb73fc1a96fce6495e5f45f281532dba2ecdc0f601cacdeff7362d90d9f26
ManifestType: installer
ManifestVersion: 1.6.0
